### ISSUE TITLE
A chaostype about pod-delete

### ISSUE THREAD

**Issue by wayyoungboy** [chaosblade-io/chaosblade-box#105]
I found another type of kill pod from chaosblade. Is this used in chaosblade-box？

**Comment by MandssS** [comment]
Yes, we will fix in next version

**Comment by wayyoungboy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wayyoungboy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
