### ISSUE TITLE
在minikube中安装agent，界面能看到minikube集群信息，但异常注入实验失败

### ISSUE THREAD

**Issue by ddd1123** [chaosblade-io/chaosblade-box#108]
**为模拟chaosblade-box对K8s集群的实验，通过使用两台同子网下的虚机1和虚机2，虚机1部署了chaosblade-box平台，虚机2部署了minikube集群，并在minikube中根据安装探针的步骤安装了探针。
至此，box平台能够看到minikube集群信息，此时通过进行实验报出如下错误**
![图片_lanxin_20220720154211](https://user-images.githubusercontent.com/49358288/179926397-7c64c9e3-e26d-43da-8bc3-9535178b30b0.png)
**此时通过查看minikube中pod信息发现chaos-agent的EXTERNAL-IP为pending，通过输入minikube tunnel后，出现了EXTERNAL-IP：**

![图片_lanxin_20220720154800](https://user-images.githubusercontent.com/49358288/179926709-7b259fb5-3f01-4685-9142-23e62c27438f.png)

**上述问题解决后，进行实验仍报连接超时：**
![图片_lanxin_20220720155024](https://user-images.githubusercontent.com/49358288/179927461-b63271bd-0aae-4cd5-b9bf-0728973bfe31.png)

**当前box平台上探针管理中minikube信息如下：**
![截图20220720155615895](https://user-images.githubusercontent.com/49358288/179929083-fece4c1a-30c6-477c-b7ab-a95f102615f0.jpg)
![截图20220720155824517](https://user-images.githubusercontent.com/49358288/179929125-3204c13c-7fc4-47d7-a27c-490fb3636313.jpg)
**故，当前问题个人分析为：minikube集群信息能够在box平台上呈现，相当于该方向的链路是通的；而从box平台通过agent向minikube进行实验的链路是不通的。
chaosblade-box版本为v1.0.1，是否支持这种集群管理方式的呢，上述流程是否存在问题呢**

**Comment by MandssS** [comment]
麻烦现在虚拟1上 

ping 172.17.0.1
ping 10.102.75.241
看下他们是否正常，看上面的信息，应该是external_ip拿到的还是cluster_ip，所以导致网络不通

**Comment by ddd1123** [comment]
感谢回复！

尝试了ping，都ping不通。我是通过minikube tunnel把external_ip暴露的，但感觉不太对，应该是minikube的问题。
换了一个其他的k8s集群，这个问题就解决了
