### ISSUE TITLE
如果 chaosblade-box 和 chaosblade-box-agent(主机安装)，需要公网访问，如何实现故障演练？

### ISSUE THREAD

**Issue by crushCoin** [chaosblade-io/chaosblade-box#109]
主机安装
chaosblade-box-agent  
第一次注册 上报 主机ip 更新 t_chaos_device 表 private_ip
https://github.com/chaosblade-io/chaosblade-box-agent/blob/main/conn/connect/connect.go#L29
之后 心跳上报 也是 主机ip  更新 t_chaos_device 表 public_ip
https://githubfast.com/chaosblade-io/chaosblade-box-agent/blob/main/conn/heartbeat/heartbeat.go#L40

ip 取值
https://github.com/chaosblade-io/chaosblade-box-agent/blob/main/pkg/options/options.go#L284
![企业微信截图_16583074218362](https://user-images.githubusercontent.com/15995863/179941462-66f3d2ec-3ff8-47a1-a3f0-06682ac50de0.png)

chaosblade-box 控制台 演练故障取 t_chaos_device 表 public_ip 值，公网如何访问呢？

**Comment by MandssS** [comment]
如果有公网ip，那么就会取公网ip来链接agent，box是先取public_IP,，如果为空，那么会取private_ip
