### ISSUE TITLE
chaosblade-box界面上evict-count、evict-percent这两个参数为啥隐藏起来？

### ISSUE THREAD

**Issue by wukaixian** [chaosblade-io/chaosblade-box#117]
我在 default_grade.json 看到`evict-count`、`evict-percent` 这两个范围参数配置了隐藏，这是为啥呢，不支持这两个参数吗？

**Comment by MandssS** [comment]
你好，目前只是因为在平台上如果可以直接指定具体机器，所以就没有暴露这几个参数
