### ISSUE TITLE
请问监控策略是否支持自行集成，相关接口的位置是否提供

### ISSUE THREAD

**Issue by ddd1123** [chaosblade-io/chaosblade-box#119]
需求详情：
1、通过chaosblade-box实现K8s集群的故障注入，在监控策略部分平台显示为空
2、当前需要进行监控行为，想咨询是否支持用户自行进行集成
3、如果支持，还想咨询这个接口是在哪里呢，平台上当前未能发现相关功能

版本情况
chaosblade-box：v1.0.1
chaos-agent：v1.0.0
chaos-operator：v1.6.0
chaos-tool：v1.6.0

thank you！

**Comment by MandssS** [comment]
1. 监控目前并没有接进来，目前我们近期没有太多精力去补充这块，如果你这边有兴趣，也可以对这块进行补充提交pr
2. 可以的，欢迎提交pr
3. 可以接入开源的prometheus，可参考v0.4.2版本

期待你的pr
