### ISSUE TITLE
这里可以支持多选并批量执行吗

### ISSUE THREAD

**Issue by kaneLi123** [chaosblade-io/chaosblade-box#122]
![image](https://user-images.githubusercontent.com/114158792/191750125-9a375a39-ed38-44d2-a4fc-72ad24185910.png)

这个页面可以支撑多选并批量执行吗

**Comment by MandssS** [comment]
支持，你选多个，然后点批量执行即可

**Comment by MandssS** [comment]
看了下，目前不支持批量运行多个演练，但一个演练中可以配置多个演练场景，在里面可以配置为“同时运行”或“顺序运行”
