### ISSUE TITLE
在kubernetes上安装探针后找不到任何应用

### ISSUE THREAD

**Issue by hantiancai** [chaosblade-io/chaosblade-box#126]
在mates节点通过helm install方式安装的探针
完整命令是：helm install agent chaos.tgz --namespace chaosblade --set env.name=test2,license=4a424d03e06d4bc2b6617c99277c3ef2,images.chaos.repository=chaosbladeio/chaosblade-agent,images.chaos.version=1.0.2,transport.endpoint=10.186.11.120:32521,controller.cluster_id=9,controller.cluster_name=rancher

安装完成之后探针管理中只能看到master节点，没有看到有其他节点的信息，在节点信息中也看不到任何pod信息。
![image](https://user-images.githubusercontent.com/64368321/196081929-69be7519-313d-4c7c-af8d-ae008b40a990.png)
![image](https://user-images.githubusercontent.com/64368321/196081973-2433e2be-ed92-49ac-8027-edf72c83cb2f.png)
对工作节点中的pod打上标签之后，在test2环境的应用管理中也看不到任何应用。
![image](https://user-images.githubusercontent.com/64368321/196082098-a0951c6b-20c1-485b-92c4-b72a5bde4ab9.png)
![image](https://user-images.githubusercontent.com/64368321/196082127-1401b5ba-6657-4369-8269-55f978273ef6.png)
但是在默认的default环境中能够看到kubernetes系统相关的应用，但是也没有打上标签的工作应用。
![image](https://user-images.githubusercontent.com/64368321/196082676-d5567c61-b1c7-46b5-a662-71f452698028.png)
**安装探针的这套kubernetes也是用来运行chaosblade-box的，在test2环境安装探针之前，在default环境也安装过，因为看不到工作节点的pod所以卸载了。**

**Comment by MandssS** [comment]
This is indeed a problem and will be fixed in the next version
