### ISSUE TITLE
chaosblade-box 部署方式安装探针疑问

### ISSUE THREAD

**Issue by HappyCodingMouse** [chaosblade-io/chaosblade-box#141]
chaosblade-box 目前安装在虚机上， 根据box界面的安装提示安装主机探针，一切正常。
我看到主机上有个文件夹chaos， 里面有个agent 还有个chaosblade；
agent这个我理解是box和chaosblade通信桥梁， box各种运行管理命令通过agent传达
chaosblade是底层的混沌能力的工具集。
现在我的疑问是，
1.chaosblade-box 目前安装在虚机上，按照box的k8s探针安装方法， 我看chaosblade-box-agent这个包，只有几个yaml配置文件， 好像没有agent和chaoblade的程序， 那这样怎么能运行管理混沌实验？
2.通过box做k8s 混沌实验，这样是不是要直接在k8s所在虚机上手动部署chaosblade， chaosblade-box-agent就是一个k8s agent，这个agent 通过 chaosblade 命令行的k8s命令进行实验，这样就不用安装chaosblade-operator了，是这样吗？

谢谢！

**Comment by MandssS** [comment]
1. k8s环境下，agent安装是通过[chaosblade-box-agent-1.0.2.tgz](https://github.com/chaosblade-io/chaosblade-box-agent/releases/download/v1.0.2/chaosblade-box-agent-1.0.2.tgz)进行安装，chaosblade则是通chaosblade-operator进行安装的
2. 不是的，agent只是一个和box端建联，并作为演练命令下发的通道，它和agent是独立的，所以如果要进行演练还是需要安装chaosblade-operator的
