### ISSUE TITLE
求助! 安装探针成功后，页面上没有显示主机

### ISSUE THREAD

**Issue by yi-guo-546** [chaosblade-io/chaosblade-box#147]
主机上安装完agent后，查看日志没有异常，ping也是成功的。

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/61730469/234785193-c55bc592-0a67-4a00-b755-73132d93e908.png">

但是在对应box页面上，没有显示出主机信息，无法进行实验
![image](https://user-images.githubusercontent.com/61730469/234785579-7914753b-c857-4827-ae43-1d3f0c93958b.png)

agent安装命令:
wget https://chaosblade.oss-cn-hangzhou.aliyuncs.com/platform/release/1.0.3/chaosagent.tar.gz -O chaos.tar.gz && tar -zxvf chaos.tar.gz -C /opt/ && sudo sh /opt/chaos/chaosctl.sh install -k 32e11418e93e463d8b2107f1e3fe5ca4 -p test  -g  test-group  -P 9527  -t  10.105.1.166:7001

chaosblade-box安装命令:
1) wget https://github.com/chaosblade-io/chaosblade-box/releases/download/v1.0.3/chaosblade-box-1.0.3.tgz
2) helm install chaosblade-box chaosblade-box-1.0.0.tgz --namespace chaosblade --set spring.datasource.password=DATASOURCE_PASSWORD

**Comment by MandssS** [comment]
1. 确定下你box打开的IP是否是 10.105.1.166:7001
2. 登陆页面的用户license 是 32e11418e93e463d8b2107f1e3fe5ca4
3. 用户的环境是否是default
![image](https://user-images.githubusercontent.com/13030286/234815244-bbfdd304-7f2a-4c03-89ce-a0000a9d08d4.png)

**Comment by yi-guo-546** [comment]
谢谢，是因为我添加了一个新环境没有生效。在default生效。
请问为什么要是default，不支持其他环境吗? 或者是哪里的配置没有对应上导致的错误。

**Comment by MandssS** [comment]
支持其他的环境，这个其实是一个全局变量的概念 eg: dev、greg等，只是你agent 启动的时候需要指定到相应的环境 -n default，只是默认是default

**Comment by yi-guo-546** [comment]
原来如此，按照默认给的安装就没加-n了。 试了下可以。谢谢，非常棒的工作。
