### ISSUE TITLE
演练场景列表显示不出任何数据，都是提示“当前分类暂无场景，请重新选择”

### ISSUE THREAD

**Issue by fukuale** [chaosblade-io/chaosblade-box#154]
演练场景列表显示不出任何数据，都是提示“当前分类暂无场景，请重新选择”，
/chaos/QuerySceneFunctionByCategoryId接口报500错误，
报错信息："\n### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'chaosblade.t_chaos_scene_authorized.authorized_id' which is not functionally dependent on columns in GROUP BY clause; 
this is incompatible with sql_mode=only_full_group_by\n### 
The error may exist in com/alibaba/chaosblade/box/dao/mapper/SceneAuthorizedMapper.java (best guess)\n### 
The error may involve defaultParameterMap\n### The error occurred while setting parameters\n### SQL: 
SELECT  authorized_id,function_id,function_name,function_code,grant_from,grant_to,permission,enabled,phase,source,function_create_time,support_host,support_k8s,is_public,
is_delete,id,gmt_create,gmt_modified  FROM t_chaos_scene_authorized     
WHERE function_id IN (?,?,?,?,?) AND ( enabled = ? ) AND (permission & 4) = 4 AND (phase & 2) > 0 AND support_k8s = ? AND is_delete = ? AND ( ( grant_to = ? AND is_public = ? ) OR 
( is_public = ? ) ) GROUP BY function_id ORDER BY function_create_time DESC\n### 
Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and 
contains nonaggregated column 'chaosblade.t_chaos_scene_authorized.authorized_id' which is not functionally dependent on columns in GROUP BY clause; 
this is incompatible with sql_mode=only_full_group_by\n; bad SQL grammar []; 
nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: 
Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'chaosblade.t_chaos_scene_authorized.authorized_id' 
which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"

**Comment by fukuale** [comment]
版本是1.0.3

**Comment by springshi1314** [comment]
这个修改下数据库的sql_mode就可以了，报错里也有提示
