### ISSUE TITLE
pod注入故障报错

### ISSUE THREAD

**Issue by dongWenTao1999** [chaosblade-io/chaosblade-box#158]
原因: `{23fdd0c44f9b8177 %!!(MISSING)s(bool=false) `getClient`: k8s exec failed, err: no matches for kind "ChaosBlade" in version "chaosblade.io/v1alpha1" [{23fdd0c44f9b8177 Error %!!(MISSING)s(int32=0) `getClient`: k8s exec failed, err: no matches for kind "ChaosBlade" in version "chaosblade.io/v1alpha1" %!!(MISSING)s(bool=false) }]}`: k8s exec failed, err: getClient%!!(MISSING)(EXTRA *meta.NoKindMatchError=no matches for kind "ChaosBlade" in version "chaosblade.io/v1alpha1")

**Comment by MandssS** [comment]
这可能是一开始卸载chaosblade-operator时，chaosblade crd资源没有清理干净导致的，可以重新卸载后重装一下，helm uninstall卸载后再执行一下 `blades=($(kubectl get blade | grep -v NAME | awk '{print $1}' | tr '\n' ' ')) && kubectl patch blade $blades --type merge -p '{"metadata":{"finalizers":[]}}'`清理一下crd资源

**Comment by jxgxldl** [comment]
> 这可能是一开始卸载chaosblade-operator时，chaosblade crd资源没有清理干净导致的，可以重新卸载后重装一下，helm uninstall卸载后再执行一下 `blades=($(kubectl get blade | grep -v NAME | awk '{print $1}' | tr '\n' ' ')) && kubectl patch blade $blades --type merge -p '{"metadata":{"finalizers":[]}}'`清理一下crd资源

请问chaosblade-operator在哪？我这边是主机部署chaosbload-box的。注入容器pod时也同样遇到这个错误。。。
