### ISSUE TITLE
系统有没有管理员帐号

### ISSUE THREAD

**Issue by 6677de88** [chaosblade-io/chaosblade-box#164]
是不是所有人都能直接注册，注册后能看到所有机器，这岂不是很危险？
有没有系统管理员帐号，能管理用户的？

**Comment by pipika110** [comment]
同问：默认的管理员账号及密码

**Comment by MandssS** [comment]
这个问题正在修复中

**Comment by MandssS** [comment]
该问题已经在1.0.5版本中进行了修复：**https://github.com/chaosblade-io/chaosblade-box/releases/tag/v1.0.5**
