### ISSUE TITLE
blade install failed

### ISSUE THREAD

**Issue by regend** [chaosblade-io/chaosblade-box#18]
在工具市场部署blade到机器上的时候失败,提示:
演练工具安装失败:[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all' [WARNING]: Could not match supplied host pattern, ignoring: 10.xx.xx.xx
机器注册方式:手动(和服务同一台机器)

**Comment by tiny-x** [comment]
手动注册 只能手动安装工具了.
