### ISSUE TITLE
手动注册机器-下载执行chaosagent报错

### ISSUE THREAD

**Issue by mCapricorn** [chaosblade-io/chaosblade-box#34]
chaosagent有arm64版本的吗？

**Comment by tiny-x** [comment]
暂时还没有，你可以拉下 master 打个 arm 包就可以。

**Comment by mCapricorn** [comment]
> 暂时还没有，你可以拉下 master 打个 arm 包就可以。

OK，已解决，谢谢。

**Comment by JustForLife** [comment]
> > 暂时还没有，你可以拉下 master 打个 arm 包就可以。
> 
> OK，已解决，谢谢。

你好，可以发我一份chaosagent的arm版本吗？
