### ISSUE TITLE
内网自动和手动安装agent失败

### ISSUE THREAD

**Issue by zxh19920616** [chaosblade-io/chaosblade-box#35]
内网搭建了一个http服务器，上面放了需要下载的文件，修改了代码和配置文件相关url，结果无论是手动还是自动安装都失败，手动安装命令如下：
wget http://xxxxxx/chaosagentctl.sh -O chaosagentctl.sh && chmod +x chaosagentctl.sh && ./chaosagentctl.sh install -r http://xxxxxx/chaosagent -t 127.0.0.1:8080
报错如下：
2021-04-01 17:11:04 [INFO]  [-rm f] /var/run/chaosagent.pid
2021-04-01 17:11:04 [INFO]  [+stop] chaosagent is stopped.
2021-04-01 17:11:04 [INFO]  [+downloading] chaosagent to [/opt/chaos/chaosagent]
2021-04-01 17:11:04 [INFO]  [+saved] chaosagent to [/opt/chaos/chaosagent]
2021-04-01 17:11:04 [INFO]  [+starting] chaosagent is starting...
2021-04-01 17:11:05 [WARN]  start failed 
./chaosagentctl.sh: line 69: exit: 2021-04-01 17:11:05 [WARN]  [start] failed:time="2021-04-01T17:06:43+08:00" level=info msg="Init config completed" time="2021-04-01T17:06:43+08:00" level=warning msg="Connection to server failed, err: connect server failed, " time="2021-04-01T17:06:43+08:00" level=warning msg="start chaos failed because of connect server failed, " time="2021-04-01T17:06:43+08:00" level=error msg="chaos agent will exit" time="2021-04-01T17:09:36+08:00" level=info msg="Init config completed" time="2021-04-01T17:09:36+08:00" level=warning msg="Connection to server failed, err: connect server failed, " time="2021-04-01T17:09:36+08:00" level=warning msg="start chaos failed because of connect server failed, " time="2021-04-01T17:09:36+08:00" level=error msg="chaos agent will exit" time="2021-04-01T17:11:04+08:00" level=info msg="Init config completed" time="2021-04-01T17:11:04+08:00" level=warning msg="Connection to server failed, err: connect server failed, " time="2021-04-01T17:11:04+08:00" level=warning msg="start chaos failed because of connect server failed, " time="2021-04-01T17:11:04+08:00" level=error msg="chaos agent will exit"

**Comment by tiny-x** [comment]
-t  的参数值是控制台的地址，确认控制台是否启动成功。
-t parameter value is the address of the console, confirm whether the console started successfully.

**Comment by fanglixuezi** [comment]
请问您最后手动装chaosagent成功了吗？
需要如何改shell脚本啊？
本人对混动工程很感兴趣，之前一直使用chaosblade工具
才发现有开源这个平台，希望能和您多沟通一下呀~

**Comment by fanglixuezi** [comment]
> 内网搭建了一个http服务器，上面放了需要下载的文件，修改了代码和配置文件相关url，结果无论是手动还是自动安装都失败，手动安装命令如下：
> wget http://xxxxxx/chaosagentctl.sh -O chaosagentctl.sh && chmod +x chaosagentctl.sh && ./chaosagentctl.sh install -r http://xxxxxx/chaosagent -t 127.0.0.1:8080
> 报错如下：
> 2021-04-01 17:11:04 [INFO] [-rm f] /var/run/chaosagent.pid
> 2021-04-01 17:11:04 [INFO] [+stop] chaosagent is stopped.
> 2021-04-01 17:11:04 [INFO] [+downloading] chaosagent to [/opt/chaos/chaosagent]
> 2021-04-01 17:11:04 [INFO] [+saved] chaosagent to [/opt/chaos/chaosagent]
> 2021-04-01 17:11:04 [INFO] [+starting] chaosagent is starting...
> 2021-04-01 17:11:05 [WARN] start failed
> ./chaosagentctl.sh: line 69: exit: 2021-04-01 17:11:05 [WARN] [start] failed:time="2021-04-01T17:06:43+08:00" level=info msg="Init config completed" time="2021-04-01T17:06:43+08:00" level=warning msg="Connection to server failed, err: connect server failed, " time="2021-04-01T17:06:43+08:00" level=warning msg="start chaos failed because of connect server failed, " time="2021-04-01T17:06:43+08:00" level=error msg="chaos agent will exit" time="2021-04-01T17:09:36+08:00" level=info msg="Init config completed" time="2021-04-01T17:09:36+08:00" level=warning msg="Connection to server failed, err: connect server failed, " time="2021-04-01T17:09:36+08:00" level=warning msg="start chaos failed because of connect server failed, " time="2021-04-01T17:09:36+08:00" level=error msg="chaos agent will exit" time="2021-04-01T17:11:04+08:00" level=info msg="Init config completed" time="2021-04-01T17:11:04+08:00" level=warning msg="Connection to server failed, err: connect server failed, " time="2021-04-01T17:11:04+08:00" level=warning msg="start chaos failed because of connect server failed, " time="2021-04-01T17:11:04+08:00" level=error msg="chaos agent will exit"

请问您最后手动装chaosagent成功了吗？
需要如何改shell脚本啊？
本人对混动工程很感兴趣，之前一直使用chaosblade工具
才发现有开源这个平台，希望能和您多沟通一下呀~

**Comment by zxh19920616** [comment]
> > 内网搭建了一个http服务器，上面放了需要下载的文件，修改了代码和配置文件相关url，结果无论是手动还是自动安装都失败，手动安装命令如下：
> > wget http://xxxxxx/chaosagentctl.sh -O chaosagentctl.sh && chmod +x chaosagentctl.sh && ./chaosagentctl.sh install -r http://xxxxxx/chaosagent -t 127.0.0.1:8080
> > 报错如下：
> > 2021-04-01 17:11:04 [INFO] [-rm f] /var/run/chaosagent.pid
> > 2021-04-01 17:11:04 [INFO] [+stop] chaosagent is stopped.
> > 2021-04-01 17:11:04 [INFO] [+downloading] chaosagent to [/opt/chaos/chaosagent]
> > 2021-04-01 17:11:04 [INFO] [+saved] chaosagent to [/opt/chaos/chaosagent]
> > 2021-04-01 17:11:04 [INFO] [+starting] chaosagent is starting...
> > 2021-04-01 17:11:05 [WARN] start failed
> > ./chaosagentctl.sh: line 69: exit: 2021-04-01 17:11:05 [WARN] [start] failed:time="2021-04-01T17:06:43+08:00" level=info msg="Init config completed" time="2021-04-01T17:06:43+08:00" level=warning msg="Connection to server failed, err: connect server failed, " time="2021-04-01T17:06:43+08:00" level=warning msg="start chaos failed because of connect server failed, " time="2021-04-01T17:06:43+08:00" level=error msg="chaos agent will exit" time="2021-04-01T17:09:36+08:00" level=info msg="Init config completed" time="2021-04-01T17:09:36+08:00" level=warning msg="Connection to server failed, err: connect server failed, " time="2021-04-01T17:09:36+08:00" level=warning msg="start chaos failed because of connect server failed, " time="2021-04-01T17:09:36+08:00" level=error msg="chaos agent will exit" time="2021-04-01T17:11:04+08:00" level=info msg="Init config completed" time="2021-04-01T17:11:04+08:00" level=warning msg="Connection to server failed, err: connect server failed, " time="2021-04-01T17:11:04+08:00" level=warning msg="start chaos failed because of connect server failed, " time="2021-04-01T17:11:04+08:00" level=error msg="chaos agent will exit"
> 
> 请问您最后手动装chaosagent成功了吗？
> 需要如何改shell脚本啊？
> 本人对混动工程很感兴趣，之前一直使用chaosblade工具
> 才发现有开源这个平台，希望能和您多沟通一下呀~

成功了，就把脚本里url改成自己搭建的文件服务器地址

**Comment by fanglixuezi** [comment]
> > > 内网搭建了一个http服务器，上面放了需要下载的文件，修改了代码和配置文件相关url，结果无论是手动还是自动安装都失败，手动安装命令如下：
> > > wget http://xxxxxx/chaosagentctl.sh -O chaosagentctl.sh && chmod +x chaosagentctl.sh && ./chaosagentctl.sh install -r http://xxxxxx/chaosagent -t 127.0.0.1:8080
> > > 报错如下：
> > > 2021-04-01 17:11:04 [INFO] [-rm f] /var/run/chaosagent.pid
> > > 2021-04-01 17:11:04 [INFO] [+stop] chaosagent is stopped.
> > > 2021-04-01 17:11:04 [INFO] [+downloading] chaosagent to [/opt/chaos/chaosagent]
> > > 2021-04-01 17:11:04 [INFO] [+saved] chaosagent to [/opt/chaos/chaosagent]
> > > 2021-04-01 17:11:04 [INFO] [+starting] chaosagent is starting...
> > > 2021-04-01 17:11:05 [WARN] start failed
> > > ./chaosagentctl.sh: line 69: exit: 2021-04-01 17:11:05 [WARN] [start] failed:time="2021-04-01T17:06:43+08:00" level=info msg="Init config completed" time="2021-04-01T17:06:43+08:00" level=warning msg="Connection to server failed, err: connect server failed, " time="2021-04-01T17:06:43+08:00" level=warning msg="start chaos failed because of connect server failed, " time="2021-04-01T17:06:43+08:00" level=error msg="chaos agent will exit" time="2021-04-01T17:09:36+08:00" level=info msg="Init config completed" time="2021-04-01T17:09:36+08:00" level=warning msg="Connection to server failed, err: connect server failed, " time="2021-04-01T17:09:36+08:00" level=warning msg="start chaos failed because of connect server failed, " time="2021-04-01T17:09:36+08:00" level=error msg="chaos agent will exit" time="2021-04-01T17:11:04+08:00" level=info msg="Init config completed" time="2021-04-01T17:11:04+08:00" level=warning msg="Connection to server failed, err: connect server failed, " time="2021-04-01T17:11:04+08:00" level=warning msg="start chaos failed because of connect server failed, " time="2021-04-01T17:11:04+08:00" level=error msg="chaos agent will exit"
> > 
> > 
> > 请问您最后手动装chaosagent成功了吗？
> > 需要如何改shell脚本啊？
> > 本人对混动工程很感兴趣，之前一直使用chaosblade工具
> > 才发现有开源这个平台，希望能和您多沟通一下呀~
> 
> 成功了，就把脚本里url改成自己搭建的文件服务器地址

请问chaosagentctl.sh脚本实怎么修改的呀？
看里面的insatll过程，在安装的时候只有下载和解压的过程
个人理解sh文件是安装chaosblade的脚本
请问是如何进行探针的安装的呀？
我应该如何改这个脚本从而安装chaosagent啊？

如果方便的话 可以加一下我嘛~~ 
13011105988（tel同vx）
好想与您探讨一下呀~~~谢谢呀！！！

**Comment by engly0** [comment]
我这是因为chaosblade-box有报错，我的mysql停掉了，脚本目前已跑通，没有问题
