### ISSUE TITLE
切换语言功能似乎有问题

### ISSUE THREAD

**Issue by angelala00** [chaosblade-io/chaosblade-box#50]
切换语言功能没有调用后端接口，刷新页面后回到了切换之前的状态

**Comment by GarfieldHuang** [comment]
+1

**Comment by xcaspar** [comment]
是的，0.3.X版本没有此问题，此问题会在下一个版本中修复。

----

Yes, 0.3.X version does not have this problem, this problem will be fixed in the next version.

**Comment by yangxiuchengv5** [comment]
新版本发布了吗？

**Comment by MandssS** [comment]
用1.0.0新版本，参见： #78
