### ISSUE TITLE
实验场景无法显示

### ISSUE THREAD

**Issue by NickHuangA** [chaosblade-io/chaosblade-box#55]
web界面：
![image](https://user-images.githubusercontent.com/66706559/124857317-ae9a1780-dfde-11eb-81ec-d39992cdf813.png)
log日志：
![image](https://user-images.githubusercontent.com/66706559/124857368-c2457e00-dfde-11eb-9aa5-de791479f561.png)

问题描述：使用‘helm del’卸载后，再次使用‘helm install’安装。创建混沌实验没有场景显示。

版本：
k8s v1.21.1
docker v19.03
chaosblade-box v0.3.2
chaosblade-operator v0.9.0

**Comment by tiny-x** [comment]
使用 0.4.1 吧
