### ISSUE TITLE
Internationality doesn't work when we choose English

### ISSUE THREAD

**Issue by wangn6** [chaosblade-io/chaosblade-box#78]
It seems only the main menu switched to English while other sub-titles/headers within the main frame are still in Chinese when we select English. See below snapshots for details:
<img width="1632" alt="internationality" src="https://user-images.githubusercontent.com/3445918/153811527-e2d3a7fc-9448-4af2-b359-c531314b9323.png">

**Comment by MandssS** [comment]
You can use 1.0.0 release, it support English switch
