### ISSUE TITLE
chaosblade-box-1.0.0.jar  Table 'chaosblade.t_chaos_m_quartz_TRIGGERS' doesn't exist

### ISSUE THREAD

**Issue by dpreal** [chaosblade-io/chaosblade-box#82]
command：
java -Duser.timezone=Asia/Shanghai -jar chaosblade-box-1.0.0.jar --spring.datasource.url=""

error log:
2022-04-24 17:31:20.621 ERROR 35123 --- [           main] c.a.c.b.d.s.BaseSchedulerService         : add scheduler failed,jobId:1518105705263927297

org.quartz.JobPersistenceException: Couldn't check for existence of job: Table 'chaosblade.t_chaos_m_quartz_TRIGGERS' doesn't exist

**Comment by coreyho** [comment]
mysql 配置/etc/my.cnf  加上lower_case_table_names=1
