### ISSUE TITLE
执行实验mysql报错

### ISSUE THREAD

**Issue by hmbyl** [chaosblade-io/chaosblade-box#85]
org.quartz.JobPersistenceException: Couldn't store trigger 'DEFAULT.1518833463308959745_trigger' for 'DEFAULT.1518833463308959745' job:Table 'chaosblade.t_chaos_m_quartz_paused_trigger_grps' doesn't exist

**Comment by MandssS** [comment]
Fix in next version

**Comment by homily707** [comment]
please assgin this issue to me @MandssS
