### ISSUE TITLE
where is chaosblade-box-fe ?

### ISSUE THREAD

**Issue by dpreal** [chaosblade-io/chaosblade-box#86]
CHAOS_PLATFORM_FE=git@github.com:chaosblade-io/chaosblade-box-fe.git
CHAOS_PLATFORM_FE_BRANCH=main

build_fe:
	rm -rf ./cache
	rm -rf chaosblade-box-starter/src/main/resources/build/*
	mkdir -p ./cache/chaosblade-box-fe
	git clone -b $(CHAOS_PLATFORM_FE_BRANCH) $(CHAOS_PLATFORM_FE) ./cache/chaosblade-box-fe

➜  tmp git clone https://github.com/chaosblade-io/chaosblade-box-fe.git
Cloning into 'chaosblade-box-fe'...
Username for 'https://github.com':

**Comment by MandssS** [comment]
Hear:  https://github.com/chaosblade-io/chaosblade-box-fe
