### ISSUE TITLE
chaosblade-box 1.0.0 前端问题

### ISSUE THREAD

**Issue by Christophernt** [chaosblade-io/chaosblade-box#87]
1、创建完演练后，点击演练，前端发出的POST /chaos/QueryExperimentAmount请求，对应的url在后端java代码中不存在，报错；
2、自己在ExperimentController里加上QueryExperimentAmount请求后，能成功触发演练，但是前端提示有问题，
![(S9)DVU{LXJBNV{SXN~HN}A](https://user-images.githubusercontent.com/24423772/165873232-ad096b7c-4917-4fee-ac22-fc6cfff21657.png)
3、能不能开源chaosblade-box 1.0.0对应的1.0.0前端，目前github只有0.4.x的，前面两个问题，目前看都是前端代码有问题，如果开源了，可以自己修改，谢谢！

**Comment by hanfanwen** [comment]
+1

**Comment by MandssS** [comment]
目前1.0.0的前端以及public，麻烦你确认下还有1、2的问题吗

**Comment by Christophernt** [comment]
> 目前1.0.0的前端以及public，麻烦你确认下还有1、2的问题吗

问题依然存在
