### ISSUE TITLE
在我的空间里点击演练，报405

### ISSUE THREAD

**Issue by tytyty123** [chaosblade-io/chaosblade-box#95]
在我的空间里，对已创建的实验，点击演练，抛405
在实验的编辑页面，点击演练，可以正常演练

<img width="511" alt="lQLPJxZuGOZdyYjM3s0D_bBY7eLo3nYzjQK1cx1DALsA_1021_222" src="https://user-images.githubusercontent.com/30776468/175234256-acc44138-9916-4a9e-9028-e58bb39e63df.png">
<img width="249" alt="lQLPJxZuGOZdyX7NAbDNAfKwIqk2epD4YQcCtXMdQcDAAA_498_432" src="https://user-images.githubusercontent.com/30776468/175234263-f2355f45-968d-40f3-9503-f8e55fcbc1bf.png">

**Comment by dolphin17** [comment]
+1，进入点演练又可以

**Comment by tytyty123** [comment]
拉最新的代码，还是有点问题


![image](https://user-images.githubusercontent.com/30776468/176616212-c1217669-709f-438d-a143-47fac6c7300c.png)

**Comment by jinyzhang5** [comment]
我也遇到了相同的问题，下载的release包版本1.0.1。这个问题修复了吗

**Comment by MandssS** [comment]
还没有release，但是已经修复了

**Comment by jinyzhang5** [comment]
我也出现了这个问题：查询资源失败 请重试。貌似是前端的问题？
操作：重新拉取了main分支的最新代码->自行打包构建部署->在我的空间中点击演练

**Comment by tytyty123** [comment]
> 我也出现了这个问题：查询资源失败 请重试。貌似是前端的问题？ 操作：重新拉取了main分支的最新代码->自行打包构建部署->在我的空间中点击演练

前端的代码还没同步到box里
得先去chaos-box-fe项目拉代码，重新编译前端程序，然后放到chao-box里build里，maven重新打包才行；
